const titles = {
    "mainheading":"Hi!",
    "subtitle":"subtitle",
    "aboutcontent":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab possimus, dicta amet, illum eius deleniti nobis non quas excepturi corporis adipisci ut rem laborum aliquid veniam, ex modi dolorem mollitia praesentium tempora aspernatur facilis soluta labore itaque. Enim voluptate corporis ad libero porro hic, ullam at ipsam voluptas, cum nam.",
    "author":"sadoon",
    "title":"nawfalozz",
    1:"كلية التمريض و الطب",
    2:"كلية الشريعة",
    3:"علوم حياتية",
    4:"كلية الكيمياء",
    5:"كلية الآداب",
    6:"كلية طب الاسنان",
    7:"كلية الصيدلة",
    8:"كلية الفيزياء",
}