const titles = {
    "mainheading":"Hi!",
    "subtitle":"subtitle",
    "aboutcontent":"خُطوة منّا إليك نخطوها، بلادٌ ستزمّلكُ دومًا، أهلًا بكَ لأردننا، لجامعتنا، ولمبادرتنا، مبادرة 'خطوة' ، فلتخطوها أنتَ باحثًا عن شغفٍ لأجله سعيت، ونساعدك نحن هُنا بخريطة تدلّك بعد نور قلبك، وفيديوهات مصوّرة توصلك لكلِّ الوجهات الممكنة في جامعتنا الأم.<br /> وفّقك الله،<br /> كُلُّ الحب، <br /> أعضاء مبادرة خُطوة <br />A step closer to you, in a country that will always serve you. Welcome to our beloved country Jordan, our university, and to our initiative “Khutwa”— a step. A step you shall take towards the passion you’ve been looking for. We’re here to help you by providing you with maps and videos that wil navigate you to each building on campus.<br />Good luck.<br /> With all love,<br /> The members of the “Khutwa” initiative.",
    "author":"sadoon",
    "title":"nawfalozz",
    1:"كلية التمريض و الطب",
    2:"كلية الشريعة",
    3:"علوم حياتية",
    4:"كلية الكيمياء",
    5:"كلية الآداب",
    6:"كلية طب الاسنان",
    7:"كلية الصيدلة",
    8:"كلية الفيزياء",
    9:"كلية الرياضة",
    10:"العيادة",
}